### ISSUE TITLE
pls help :>

### ISSUE THREAD

**Issue by ukrolelo** [tower9/hostblock#4]
Greetings!
Awesome app man ! its working so well!!! i am now putting it on all of my servers :>>>
Please can you explain to me something as my skill is low on c++ to read in source.
1.
What is the difference between
log.refused.pattern and log.pattern ?

2.Why it is saying
Matched blocked access pattern, but no previous information about suspicious activity, skipping...
But supposed to block the IP as per rule -> syslog (i checked the regex its fine):
log.refused.pattern = ^.+? \[DROP] .+? SRC=%i .+? DPT=21 .+?
log.refused.score = 10

3.
Top 5 most active addresses:
----------------------------------------------------------------------------------------
     Address     | Count | Score  | Refused |    Last activity    |       Status
----------------------------------------------------------------------------------------
 61.163.11.172   |  68   | 489210 |    0    | 2021-05-27 16:13:22 | 2021-06-02 08:06:52
 138.68.138.162  |  66   | 391112 |    0    | 2021-05-27 19:51:40 | 2021-06-01 08:30:12
 143.198.129.231 |  23   | 36000  |    1    | 2021-05-27 20:42:08 |
 64.140.118.241  |  22   |   0    |    0    | 2021-05-27 19:51:40 |
 23.129.64.234   |  20   |   0    |    0    | 2021-05-27 19:51:40 |

Last activity:
---------------------------------------------------------------------------------------
     Address     | Count | Score | Refused |    Last activity    |       Status
---------------------------------------------------------------------------------------
 189.39.57.105   |   0   | 36000 |    1    | 2021-05-27 22:25:08 |
 172.104.242.173 |   0   | 71340 |    2    | 2021-05-27 22:05:38 | 2021-05-28 17:54:38
 209.141.58.231  |   2   |   0   |    0    | 2021-05-27 22:00:38 |
 45.35.130.62    |   1   | 64982 |    2    | 2021-05-27 21:42:38 | 2021-05-28 15:45:40
 185.220.103.6   |   2   | 14400 |    0    | 2021-05-27 21:34:08 |

The score is to calculate time for ban?
Status mean ban until?
Why the 14400 is not ban then?
What does Refused mean?Repeating attempts?

Thank you ! <3

**Comment by tower9** [comment]
Hi!

> 1. What is the difference between log.refused.pattern and log.pattern ?

I like counting separately suspicious activity and how many times that address has been blocked. Just two separate counters for each IP address. `log.pattern` matches increase "Count", `log.refused.pattern` increase "Refused":
```
-------------------------------------------------------------------------------------------
     Address     | Count |   Score   | Refused |    Last activity    |       Status        
-------------------------------------------------------------------------------------------
```

> 2.Why it is saying
> Matched blocked access pattern, but no previous information about suspicious activity, skipping...
> But supposed to block the IP as per rule -> syslog (i checked the regex its fine):
> log.refused.pattern = ^.+? [DROP] .+? SRC=%i .+? DPT=21 .+?
> log.refused.score = 10

He he, that is old leftover )) - initially I wanted to ignore refused access matches if there haven't been any history of suspicious activity for that address previously. Haven't reconsidered ever since, but I guess better to remove this logic.

> The score is to calculate time for ban?
> Status mean ban until?
> Why the 14400 is not ban then?
> What does Refused mean?Repeating attempts?

There are two modes how to block:
1. Without score multiplier `address.block.multiplier = 0`
In this case each pattern match simply increases score and if score exceeds `address.block.score`, then iptables rule is created to block access.
2. But I also wanted an option to not block access permanently, but based on time since last suspicious activity. For this I introduced score multiplier, e.g. `address.block.multiplier = 3600`
Multiplier increases score specified number of times and in this mode score is used to check how many seconds have passed since suspicious activity and to automatically remove iptables rule after it expires. Status shows when iptables rule to be removed. On next pattern match hostblock looks at previously calculated score, substracts from score based on how much time has passed (seconds) and adds new score multiplied with score multplier.

**Comment by ukrolelo** [comment]
Omg, genius :>

I needed to seperate the main iptables log from already blocked HB_LOG_AND_DROP;
I have send a pull request but that can make your logic stop working as i can see.
Or i can just make 2 rules in confing one for iptables.log and one for hostblock.log
The iptables.log will report to abuseipdb and save to hostblock chain.
The hostblock.log will just count the suspition.
Because of  this seperation i now understand which IPs are already banned and which are new scouting arround.

**Comment by ukrolelo** [comment]
36.90.209.109   | 2019  | 1085008169 |    0    | 2021-05-29 15:46:22 | 2055-10-16 14:55:51

2055 xD
If it will be unbanned from abuseipdb will it unban my HB_LOG_AND_DROP rule? Or the 2055 is fixed until i delete the hostblock.data ?
